---
name: Mitchell Hillman
title: Senior UI Developer
location: Charlottesville, Virginia
phone: "(608) 322-9118"
email: mitchellhillman@gmail.com
url: www.mitchellhillman.com
about: Multi-talented software engineer with an emphasis in front end technologies
  and a background in design
skills:
- Accessibility
- Branding
- Content Strategy
- Cross-browser Testing
- Project Management
- Software Architecture
- Test Driven Development
- Training
- User Testing
- UX Design
tools:
- React
- Storybook
- Webpack
- JSS
- SASS / LESS
- NPM
- WCAG 2.0 / 508
- LAMP
- ES6
- React Testing Library
- Jest
jobs:
- company: Bottomline Technologies
  title: Senior UI Developer
  location: Charlottesville, Virginia
  description: Develop library of shared UI assets used by enterprise banking and
    payment management applications across multiple lines of business within a global
    corporation
  start: 04/2019
  end: Present
- company: Room Key
  title: Lead UI Developer
  location: Charlottesville, Virginia
  description: Responsible for design and development of new product features built
    in a React/Redux single page app. Was involved in software architecture and general
    product strategy discussions. Duties included mentoring team members, code review,
    and feature execution.
  start: 05/2016
  end: 01/2018
- company: Silverchair
  title: UI Development Manager
  location: Charlottesville, Virginia
  description: Team lead of 7 UI developers. Created white labeled themes for custom-built
    online publishing platform
  start: 09/2014
  end: 05/2016
- company: CFA Institute (Contractor)
  title: UX Designer and Developer
  location: Charlottesville, Virginia
  description: Design web interfaces for a global organization with a focus on user
    testing and data driven strategies
  start: 05/2014
  end: 09/2014
- company: Journey Group, Inc.
  title: Web Developer
  location: Charlottesville, Virginia
  description: Develop custom publishing platforms. Work included UX design, information
    architecture and custom Drupal implimentations.
  start: 05/2013
  end: 04/2014
- company: Venveo
  title: Front End Developer
  location: Blacksburg, Virginia
  description: Develop HTML/CSS implimentation of custom themes for marketing websites
  start: 02/2012
  end: 05/2013
- company: Schrader International (Contractor)
  title: Graphic Designer
  location: Alta Vista, Virginia
  description: Design product catalog (online and print), brand guideline manual,
    sales literature and trade show displays
  start: 08/2010
  end: 06/2011
education:
- degree: B.S., Public Relations, Advertising, and Applied Communication
  school: Liberty University
  start: 1/2008
  end: 5/2011
